# Generated by Django 5.1.1 on 2024-10-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_porta_testimonios'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonios',
            name='empresa',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='testimonios',
            name='puesto',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
