# Generated by Django 5.1.1 on 2024-10-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_testimonios_empresa_testimonios_puesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonios',
            name='empresa',
            field=models.CharField(default='--', max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonios',
            name='puesto',
            field=models.CharField(default='--', max_length=100),
        ),
    ]
